name: "@astro-kitchen/monorepo"
description: "Astro Kitchen"
private: true
license: MPL-2.0
author: nuin
scripts:
  dev: pnpm "/^dev:.*/"
  dev:website: 'pnpm --filter website dev'
  dev:vanilla: 'pnpm --filter vanilla dev'

  build: pnpm "/^build:.*/"
  build:website: >-
    pnpm --filter website install &&
    pnpm --filter website build
  build:vanilla: >-
    pnpm --filter vanilla install &&
    pnpm --filter vanilla build &&
    cp -r ./apps/vanilla/dist ./dist/vanilla

  preview: pnpm build && wrangler dev

  check: >-
    biome check ;
    dprint check
  format: >-
    biome format --write ;
    dprint fmt
  lint: biome lint --write

packageManager: "pnpm@10.28.0"
engines:
  node: ">=24.0.0"
  pnpm: ">=10.0.0"

devDependencies:
  "@biomejs/biome": "catalog:"
  dprint: "catalog:"
  wrangler: "catalog:"
