name: "@astro-kitchen/monorepo"
description: "Astro Kitchen"
private: true
license: MPL-2.0
author: nuin
scripts:
  dev: pnpm "/^dev:.*/"

  build: pnpm "/^build:.*/"

  preview: pnpm build && wrangler dev

  format: biome format --write
  lint: biome lint --write

packageManager: "pnpm@10.28.0"
engines:
  node: ">=24.0.0"
  pnpm: ">=10.0.0"

devDependencies:
  "@biomejs/biome": "catalog:"
  wrangler: "catalog:"
