packages:
  - "apps/*"
  - "packages/*"
  - "website"

catalog:
  "@types/node": ^25.1.0
  vite: ^7.3.1
  wrangler: ^4.61.1

  # ----- Linter / Formatter -----
  "@biomejs/biome": 2.3.13
  dprint: ^0.51.1

catalogs:
  astro:
    astro-relative-links: ^0.4.2

  astro5:
    astro: ^5.17.1

onlyBuiltDependencies:
  - esbuild
