packages:
  - "apps/*"
  - "packages/*"
  - "website"

catalog:
  vite: ^7.3.1
  wrangler: ^4.61.1

  # ----- Linter / Formater -----
  "@biomejs/biome": 2.3.13

catalogs:
  astro:
    astro-relative-links: ^0.4.2

  astro5:
    astro: ^5.17.1

onlyBuiltDependencies:
  - esbuild
