packages:
  - "apps/*"
  - "packages/*"
  - "website"

catalog:
  vite: ^7.3.1
  wrangler: ^4.60.0

  # ----- Linter / Formater -----
  "@biomejs/biome": 2.3.12

catalogs:
  astro:
    astro-relative-links: ^0.4.2

  astro5:
    astro: ^5.16.15

onlyBuiltDependencies:
  - esbuild
